(()=>{
const API='https://bellissimopizza.avcoindustries.com/api/menus/1/light',BACKUP='../assets/menu-fallback.json',mode=document.body.dataset.menuMode||'regular',grid=document.getElementById('menuGrid'),nav=document.getElementById('categoryNav'),note=document.getElementById('liveNote');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),isCatering=n=>/cater|tray|party/i.test(n);let current=[];
function addToolbar(){if(document.querySelector('.menu-toolbar'))return;const bar=document.createElement('div');bar.className='menu-toolbar';bar.innerHTML=`<input class="menu-search" id="menuSearch" type="search" placeholder="Search the menu…" aria-label="Search the menu"><div class="menu-tools"><span class="menu-count" id="menuCount"></span><a class="menu-pdf-button" href="${mode==='catering'?'../catering-menu.pdf':'../menu.pdf'}" target="_blank" rel="noopener">View printable PDF</a></div>`;grid.before(bar);document.getElementById('menuSearch').addEventListener('input',e=>draw(current,e.target.value))}
function draw(cats,query=''){const q=query.trim().toLowerCase(),filtered=cats.map(c=>({...c,items:c.items.filter(i=>!q||`${i.name} ${i.description||''} ${c.name}`.toLowerCase().includes(q))})).filter(c=>c.items.length),total=filtered.reduce((n,c)=>n+c.items.length,0);document.getElementById('menuCount').textContent=`${total} ${total===1?'item':'items'}`;nav.innerHTML=filtered.map((c,i)=>`<button class="${i?'':'active'}" data-target="${slug(c.name)}">${esc(c.name)}</button>`).join('');grid.innerHTML=filtered.length?filtered.map(c=>`<article class="menu-category ${mode==='catering'?'catering-category':''}" id="${slug(c.name)}"><h2>${esc(c.name)}</h2>${mode==='catering'?'<div class="tray-head"><span></span><span>Small</span><span>Large</span></div>':''}${c.items.map(i=>`<div class="dish ${mode==='catering'?'catering-dish':''}"><span class="dish-name">${esc(i.name)}</span>${mode==='catering'?`<span class="dish-price">${i.small?`$${esc(i.small)}`:'—'}</span><span class="dish-price">${i.large?`$${esc(i.large)}`:'—'}</span>`:`<span class="dish-price">$${Number(i.price).toFixed(2)}</span>`}${i.description?`<span class="dish-desc">${esc(i.description)}</span>`:''}</div>`).join('')}</article>`).join(''):'<article class="menu-category"><h2>No matches</h2><p>Try another dish, ingredient or category.</p></article>';nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'});nav.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b))})}
function show(cats){current=cats;addToolbar();draw(current)}
function showCatering(){show(window.BELLISSIMO_CATERING_MENU.map(c=>({name:c.name,items:c.items.map(([name,small,large,description])=>({name,small,large,description}))})));note.innerHTML='<span class="live-dot"></span>Complete catering menu'}
if(mode==='catering'){const source=document.createElement('script');source.src='../assets/catering-menu-data.js';source.onload=showCatering;source.onerror=()=>grid.innerHTML='<article class="menu-category"><h2>Catering menu</h2><p>Please call <a href="tel:+16318861536">(631) 886-1536</a> or view the printable menu.</p></article>';document.head.appendChild(source);return}
function categories(data){return(Array.isArray(data)?data:[data]).flatMap(m=>m.subcategories||[]).filter(c=>!c.isDeleted&&!isCatering(c.name)).sort((a,b)=>(a.displayOrder||0)-(b.displayOrder||0)).map(c=>({...c,items:(c.items||[]).filter(i=>i.isActive!==false&&!i.isDeleted).sort((a,b)=>(a.displayOrder||0)-(b.displayOrder||0))})).filter(c=>c.items.length)}
fetch(API,{mode:'cors'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>show(categories(d))).catch(()=>fetch(BACKUP).then(r=>r.json()).then(d=>show(categories(d))).catch(()=>{grid.innerHTML='<article class="menu-category"><h2>Call for today’s menu</h2><p>Our team will be happy to help at <a href="tel:+16318861536">(631) 886-1536</a>.</p></article>'}));
})();
