const header=document.getElementById('site-header');
const enhancement=document.createElement('link');enhancement.rel='stylesheet';enhancement.href=location.pathname==='/'?'enhancements.css':'../enhancements.css';document.head.appendChild(enhancement);
const finalPolish=document.createElement('link');finalPolish.rel='stylesheet';finalPolish.href=location.pathname==='/'?'polish.css':'../polish.css';document.head.appendChild(finalPolish);
const mapPolish=document.createElement('link');mapPolish.rel='stylesheet';mapPolish.href=location.pathname==='/'?'map-polish.css':'../map-polish.css';document.head.appendChild(mapPolish);
const canonicalPath=location.pathname.includes('/menu')?'/menu/':location.pathname.includes('/catering')?'/catering/':location.pathname.includes('/visit')?'/visit/':'/';if(!document.querySelector('link[rel="canonical"]')){const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=`https://www.bellissimospizzeria.com${canonicalPath}`;document.head.appendChild(canonical)}if(!document.querySelector('meta[name="robots"]')){const robots=document.createElement('meta');robots.name='robots';robots.content='index, follow, max-image-preview:large';document.head.appendChild(robots)}
document.querySelectorAll('.store-badge').forEach(badge=>{const icon=badge.querySelector('.store-icon');if(!icon)return;if(badge.href.includes('apple.com'))icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M17.1 12.5c0-2.2 1.8-3.3 1.9-3.4-1-1.5-2.6-1.7-3.2-1.7-1.4-.1-2.7.8-3.4.8-.7 0-1.7-.8-2.9-.8-1.5 0-2.9.9-3.7 2.3-1.6 2.7-.4 6.8 1.1 9 .8 1.1 1.7 2.3 2.9 2.2 1.2 0 1.6-.7 3.1-.7 1.4 0 1.9.7 3.1.7 1.3 0 2.1-1.1 2.8-2.2.9-1.3 1.2-2.6 1.2-2.7-.1 0-2.9-1.1-2.9-3.5ZM14.9 6c.6-.8 1.1-1.9.9-3-1 .1-2.2.7-2.9 1.5-.6.7-1.1 1.8-1 2.9 1.1.1 2.3-.6 3-1.4Z"/></svg>';else icon.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#34A853" d="M3 2.5v19l10.8-9.5z"/><path fill="#4285F4" d="m13.8 12 3.1-2.7L5.2 2.7z"/><path fill="#FBBC04" d="m13.8 12-8.6 9.3 11.7-6.6z"/><path fill="#EA4335" d="m16.9 9.3-3.1 2.7 3.1 2.7 3.7-2.1c.6-.3.6-1.1 0-1.5z"/></svg>'});
if(location.pathname.includes('/visit')){const map=document.querySelector('.map-card');if(map){map.outerHTML='<div class="embedded-map"><iframe title="Map to Bellissimo Pizzeria & Pasta at The Shoppes at East Wind" src="https://www.google.com/maps?q=Bellissimo+Pizzeria+%26+Pasta,+5768+Route+25A,+Wading+River,+NY+11792&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><a href="https://maps.google.com/?q=5768+Route+25A+Wading+River+NY+11792"><strong>Open full map</strong><span>Get turn-by-turn directions →</span></a></div>'}}
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});
document.querySelectorAll('a[href="../#visit"]').forEach(link=>link.setAttribute('href','../visit/'));
const toggle=document.getElementById('menuToggle'),nav=document.getElementById('siteNav');
toggle?.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
if(document.body.dataset.menuMode==='regular'){const menuTitle=document.querySelector('.page-hero h1');if(menuTitle)menuTitle.innerHTML='<em>Menu</em>';document.getElementById('liveNote')?.remove()}
if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e))}else document.querySelectorAll('.reveal').forEach(e=>e.classList.add('in'));
